[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "QuantumSheets"
version = "0.1.17"
description = "Displaying quantum circuits with classical notes"
authors = [
    { name = "Ben Bar" }
]
dependencies = [
    "qiskit",
    "matplotlib",
    "numpy",
]
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"

[project.scripts]
quantumsheets = "QuantumSheets.cli:main"

[tool.setuptools.package-data]
QuantumSheets = ["*.png", "*.otf"]
